/**
 * Vector repository (ChromaDB). Encapsulates all vector-store access: collection
 * lifecycle, chunk upserts, similarity search, and per-document deletion.
 *
 * Embeddings are generated by the embedding service and passed explicitly, so
 * the collection's embedding function is only a fallback for text-based calls.
 */
import type { ChromaClient, Collection } from 'chromadb';
import { env } from '../config/index.js';
import { logger } from '../utils/logger.js';
import { withRetry } from '../utils/retry.js';
import { getChromaClient } from '../integrations/chroma.js';
import { embeddingService } from '../services/embedding.service.js';

export interface ChunkRecord {
  chunkId: string;
  documentId: string;
  text: string;
  pageNumber: number | null;
  chunkIndex: number;
  category: string;
  title: string;
  originalName: string;
  fileType: string;
}

export interface VectorMatch {
  chunkId: string;
  documentId: string;
  text: string;
  score: number;
  pageNumber: number | null;
  title: string;
  originalName: string;
  category: string;
}

// Custom embedding function so ChromaDB never falls back to its default
// (model-downloading) embedder. Delegates to our Gemini-backed service.
const embeddingFunction = {
  generate: (texts: string[]): Promise<number[][]> => embeddingService.embedDocuments(texts),
};

class VectorRepository {
  private collection: Collection | null = null;

  private async getCollection(): Promise<Collection> {
    if (this.collection) return this.collection;
    const client: ChromaClient = getChromaClient();
    this.collection = await client.getOrCreateCollection({
      name: env.CHROMA_COLLECTION,
      metadata: { 'hnsw:space': 'cosine', description: 'INDUS-BRAIN AI knowledge chunks' },
      embeddingFunction: embeddingFunction as never,
    });
    logger.info('ChromaDB collection ready', { collection: env.CHROMA_COLLECTION });
    return this.collection;
  }

  /**
   * Insert chunk vectors. Embeddings must align by index with `chunks`.
   */
  async upsertChunks(chunks: ChunkRecord[], embeddings: number[][]): Promise<void> {
    if (chunks.length === 0) return;
    const collection = await this.getCollection();

    const ids = chunks.map((c) => c.chunkId);
    const documents = chunks.map((c) => c.text);
    const metadatas = chunks.map((c) => {
      const meta: Record<string, string | number | boolean> = {
        documentId: c.documentId,
        chunkIndex: c.chunkIndex,
        category: c.category,
        title: c.title,
        originalName: c.originalName,
        fileType: c.fileType,
      };
      if (c.pageNumber !== null) meta.page = c.pageNumber;
      return meta;
    });

    await withRetry(() => collection.upsert({ ids, embeddings, documents, metadatas }), {
      label: 'chroma-upsert',
      retries: 3,
    });
    logger.info('Upserted chunks into vector store', { count: chunks.length });
  }

  /**
   * Similarity search. Returns matches ordered by descending cosine similarity.
   */
  async query(
    queryEmbedding: number[],
    topK: number,
    filter?: Record<string, string>,
  ): Promise<VectorMatch[]> {
    const collection = await this.getCollection();

    const result = await withRetry(
      () =>
        collection.query({
          queryEmbeddings: [queryEmbedding],
          nResults: topK,
          ...(filter ? { where: filter } : {}),
        }),
      { label: 'chroma-query', retries: 2 },
    );

    const ids = result.ids?.[0] ?? [];
    const documents = result.documents?.[0] ?? [];
    const distances = result.distances?.[0] ?? [];
    const metadatas = result.metadatas?.[0] ?? [];

    return ids.map((id, i) => {
      const meta = (metadatas[i] ?? {}) as Record<string, unknown>;
      const distance = distances[i];
      const score = typeof distance === 'number' ? Math.max(0, 1 - distance) : 0;
      const pageValue = meta.page;
      return {
        chunkId: id,
        documentId: typeof meta.documentId === 'string' ? meta.documentId : '',
        text: documents[i] ?? '',
        score,
        pageNumber: typeof pageValue === 'number' ? pageValue : null,
        title: typeof meta.title === 'string' ? meta.title : 'Untitled',
        originalName: typeof meta.originalName === 'string' ? meta.originalName : '',
        category: typeof meta.category === 'string' ? meta.category : 'general',
      };
    });
  }

  /**
   * Fetch all stored chunks for a single document (no similarity ranking),
   * ordered by chunk index. Used to assess a regulation's full requirement set.
   */
  async getByDocument(documentId: string, limit: number): Promise<VectorMatch[]> {
    const collection = await this.getCollection();
    const result = await withRetry(() => collection.get({ where: { documentId }, limit }), {
      label: 'chroma-get',
      retries: 2,
    });

    const ids = result.ids ?? [];
    const documents = result.documents ?? [];
    const metadatas = result.metadatas ?? [];

    const chunks = ids.map((id, i) => {
      const meta = (metadatas[i] ?? {}) as Record<string, unknown>;
      const pageValue = meta.page;
      return {
        chunkId: id,
        documentId,
        text: documents[i] ?? '',
        score: 1,
        pageNumber: typeof pageValue === 'number' ? pageValue : null,
        title: typeof meta.title === 'string' ? meta.title : 'Untitled',
        originalName: typeof meta.originalName === 'string' ? meta.originalName : '',
        category: typeof meta.category === 'string' ? meta.category : 'general',
      };
    });

    // chunkId is `${documentId}:${chunkIndex}` — restore document order.
    return chunks.sort((a, b) => {
      const ai = Number(a.chunkId.split(':').pop());
      const bi = Number(b.chunkId.split(':').pop());
      return ai - bi;
    });
  }

  /** Remove all chunks belonging to a document. */
  async deleteByDocument(documentId: string): Promise<void> {
    const collection = await this.getCollection();
    await withRetry(() => collection.delete({ where: { documentId } }), {
      label: 'chroma-delete',
      retries: 2,
    });
    logger.info('Deleted document chunks from vector store', { documentId });
  }

  /** Total number of indexed chunks. */
  async count(): Promise<number> {
    const collection = await this.getCollection();
    return collection.count();
  }
}

export const vectorRepository = new VectorRepository();
